---
- name: Install dotnet per user
  ansible.builtin.include_tasks: install.yml
  loop: "{{ identity_users_resolved }}"
  loop_control:
    label: "{{ item.name }}"
  vars:
    user: "{{ item }}"
  when:
    - user != {}
