---
namespace: mps
name: development
version: 0.3.1
readme: README.md
authors:
  - foo <bar@baz.com>
description: Development tooling — SDKs, CLIs, IDEs
license:
  - GPL-3.0-or-later
tags:
  - linux
  - development
  - dev
  - dotnet
  - espidf
  - java
  - latex
  - lmstudio
  - opencode
  - unity
  - mps
repository: https://github.com/my-perfect-system/mps-development
documentation: https://github.com/my-perfect-system/mps-development
homepage: https://github.com/my-perfect-system/mps-development
issues: https://github.com/my-perfect-system/mps-development/issues
build_ignore:
  .ansible-lint
  .yamllint
  - .git
  - .github
  - .gitignore
  - "*.tar.gz"
  - .ansible
dependencies:
  mps.base: ">=0.1.0"
  ansible.posix: ">=1.0.0"
