---
- name: Install java packages per user
  vars:
    user: "{{ item }}"
  block:
    - name: Install java packages
      ansible.builtin.package:
        name: "{{ java_packages }}"
        state: present
        update_cache: true
      become: true
  loop: "{{ identity_users_resolved | mps_filter_users('development_java') }}"
  loop_control:
    label: "{{ item.name }}"
