---
- name: "DEV_JAVA_MAIN - Install JDK/JRE per user"
  ansible.builtin.include_tasks: install.yml
  loop: "{{ identity_users_resolved }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - entity.user_roles.development_java | default(false)
    - entity.state == 'present'
  vars:
    user: "{{ item }}"
