---
- name: Install latex packages per user
  vars:
    user: "{{ item }}"
  block:
    - name: Install latex packages
      ansible.builtin.package:
        name: "{{ latex_packages }}"
        state: present
        update_cache: true
      become: true
  loop: "{{ identity_users_resolved | mps_filter_users('development_latex') }}"
  loop_control:
    label: "{{ item.name }}"
