---
- name: "DEV_UNITY_MAIN - Install Unity Hub (and VSCode) per user"
  ansible.builtin.include_tasks: install.yml
  loop: "{{ identity_users_resolved }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - entity.user_roles.development_unity | default(false)
    - entity.state == 'present'
  vars:
    user: "{{ item }}"
