---
- name: Development full install
  hosts: all
  become: true
  roles:
    - role: mps.development.opencode
    - role: mps.development.java
    - role: mps.development.dotnet
    - role: mps.development.espidf
    - role: mps.development.latex
    - role: mps.development.lmstudio
    - role: mps.development.unity
